version: '3'
name: test
services:
  mysql:
    image: mysql:8.0.34
    networks:
      - khds_network
    volumes:
      - ./e-commerce/db/conf.d:/etc/mysql/conf.d
      - ./e-commerce/db/data:/var/lib/mysql
      - ./e-commerce/db/initdb.d:/docker-entrypoint-initdb.d
    env_file: ./e-commerce/.env
    ports:
      - "3306:3306"
    restart: always
  backend:
    build:
      context: ./e-commerce
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - khds_network
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/khds_pay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=mysqluser
      - SPRING_DATASOURCE_PASSWORD=mysqlpw
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    restart: always
  frontend:
    depends_on:
      - backend
    build:
      context: ./my-app
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - khds_network
  nginx:
    container_name: nginx
    image: nginx:latest
    networks:
      - khds_network
    restart: always
    volumes:
      - ./conf/:/etc/nginx/conf.d
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

networks:
  khds_network:
    driver: bridge